### PR TITLE
Solution

### PR DESCRIPTION
**Pull request by salaxambar**

### CODE REVIEW

**Review by YuriiSmolii — COMMENTED** [review]
Why the PR is closed?

**Comment by salaxambar** [comment]
> Why the PR is closed?

I created new repository to make this task and closed my last try.

**Comment by YuriiSmolii** [comment]
> > Why the PR is closed?
> 
> I created new repository to make this task and closed my last try.

Got it, but Mate platform cannot handle it. You should reopen this one and push the completed task here.

**Review by YuriiSmolii — COMMENTED** [review]
.

**Comment by salaxambar** [comment]
> > > Why the PR is closed?
> > 
> > 
> > I created new repository to make this task and closed my last try.
> 
> Got it, but Mate platform cannot handle it. You should reopen this one and push the completed task here.

image
What should I do?

**Comment by salaxambar** [comment]
Reopen

**Comment by salaxambar** [comment]
image
What should i do? I can't open it again.

**Pull request closed without merging**
